name: riverpod_theme_switcher
description: "Riverpod Theme Switcher"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.5.0-236.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
